services:
  db:
    container_name: quest-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=quest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    networks:
      - apiprogram
  api:
    container_name: quest-api
    build:
      context: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    networks:
      - apiprogram

networks:
  apiprogram:
